# Generated by Django 3.1.1 on 2020-09-12 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('points_scored', models.IntegerField(default=0)),
                ('questions_attempted', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
