# Generated by Django 3.1.1 on 2020-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200913_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='questions_attempted',
            field=models.CharField(max_length=200),
        ),
    ]
