# Generated by Django 3.1.1 on 2020-09-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200913_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='Extras', max_length=75)),
                ('description', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='questions_attempted',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontype'),
            preserve_default=False,
        ),
    ]
