# Generated by Django 3.1.1 on 2020-09-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200913_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='Subject',
        ),
    ]
