# Generated by Django 2.1.15 on 2020-09-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200917_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='questions_attempted',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
